// Generated by gencpp from file rplidar_ros/Distance.msg
// DO NOT EDIT!


#ifndef RPLIDAR_ROS_MESSAGE_DISTANCE_H
#define RPLIDAR_ROS_MESSAGE_DISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rplidar_ros
{
template <class ContainerAllocator>
struct Distance_
{
  typedef Distance_<ContainerAllocator> Type;

  Distance_()
    : distance(0.0)
    , angle(0.0)  {
    }
  Distance_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , angle(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef float _angle_type;
  _angle_type angle;




  typedef boost::shared_ptr< ::rplidar_ros::Distance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rplidar_ros::Distance_<ContainerAllocator> const> ConstPtr;

}; // struct Distance_

typedef ::rplidar_ros::Distance_<std::allocator<void> > Distance;

typedef boost::shared_ptr< ::rplidar_ros::Distance > DistancePtr;
typedef boost::shared_ptr< ::rplidar_ros::Distance const> DistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rplidar_ros::Distance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rplidar_ros::Distance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rplidar_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rplidar_ros': ['/home/yangjian/catkin_ws/src/rplidar_ros/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rplidar_ros::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::Distance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rplidar_ros::Distance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::Distance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rplidar_ros::Distance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rplidar_ros::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ec24e737ddaa2f1769f4aa74f864401d";
  }

  static const char* value(const ::rplidar_ros::Distance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xec24e737ddaa2f17ULL;
  static const uint64_t static_value2 = 0x69f4aa74f864401dULL;
};

template<class ContainerAllocator>
struct DataType< ::rplidar_ros::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rplidar_ros/Distance";
  }

  static const char* value(const ::rplidar_ros::Distance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rplidar_ros::Distance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
float32 angle\n\
";
  }

  static const char* value(const ::rplidar_ros::Distance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rplidar_ros::Distance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.angle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Distance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rplidar_ros::Distance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rplidar_ros::Distance_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RPLIDAR_ROS_MESSAGE_DISTANCE_H
